[build]
# Specify the Nixpacks instance you want to use for building your project.
instance = "python311"

[install]
# Installation command for setting up your environment and installing dependencies.
# You can customize this command to match your project's setup.
command = """
  python -m venv --copies /opt/venv && . /opt/venv/bin/activate
  && pip install -r requirements.txt
"""

[start]
# Command to start your application. Customize this as per your project's requirements.
command = "uvicorn main:app --host 0.0.0.0 --port $PORT"